version: "3"

services:
  db:
    image: postgres:9.6
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=deliveryMercado

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "9090:9090"
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend/delivery-mercado
      dockerfile: Dockerfile
    expose:
      - "80"
    ports:
      - "80:80"
    links:
      - backend
    depends_on:
      - backend
